/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.15
 * Generated at: 2023-11-01 19:10:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class studentForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/footer.jsp", Long.valueOf(1698865822215L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1698865822217L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("  <head>\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("    <title>Bootstrap demo</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\n");
      out.write("  </head>\n");
      out.write("  <body>\n");
      out.write("    \n");
      out.write("      <nav class=\"navbar navbar-expand-lg bg-light\">\n");
      out.write("  <div class=\"container-fluid\">\n");
      out.write("    <a class=\"navbar-brand\" href=\"#\">Navbar</a>\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link active\" aria-current=\"page\" href=\"home.jsp\">Home</a>\n");
      out.write("        </li>\n");
      out.write("<!--        <li class=\"nav-item\">\n");
      out.write("            <a class=\"nav-link\" href=\"home.jsp\">Home</a>\n");
      out.write("        </li>-->\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n");
      out.write("            Student\n");
      out.write("          </a>\n");
      out.write("          <ul class=\"dropdown-menu\">\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"studentForm.jsp\">Student Form</a></li>\n");
      out.write("              <li><a class=\"dropdown-item\" href=\"studentAddView.jsp\">Student View</a></li>\n");
      out.write("            <li><hr class=\"dropdown-divider\"></li>\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"#\">Something else here</a></li>\n");
      out.write("          </ul>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item\">\n");
      out.write("          <a class=\"nav-link disabled\">Disabled</a>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <form class=\"d-flex\" role=\"search\">\n");
      out.write("        <input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\" aria-label=\"Search\">\n");
      out.write("        <button class=\"btn btn-outline-success\" type=\"submit\">Search</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("</nav>\n");
      out.write("      \n");
      out.write("      \n");
      out.write("      \n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\n");
      out.write("  </body>\n");
      out.write("</html>\n");
      out.write("        \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container my-3\">\n");
      out.write("    <div class=\"bg-success text-center\">\n");
      out.write("        <div style=\"color: white\">\n");
      out.write("            <h class=\"jumborton \">Student Form</h>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!--    -- form start---->\n");
      out.write("\n");
      out.write("    <form style=\"background-color: beige\">\n");
      out.write("\n");
      out.write("        <!--        --1st row start-->\n");
      out.write("        <div class=\"row mt-3\">\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <label  class=\"form-label\">First Name</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"firstName\" name=\"givenName\" placeholder=\"First Name\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <label  class=\"form-label\">Last Name</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"lastName\" name=\"lastName\" placeholder=\"Last Name\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!--        --1st row end-->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!--        --2nd row start-->\n");
      out.write("        <div class=\"row mt-3\">\n");
      out.write("<!--  <div class=\"col-md-6\">-->\n");
      out.write("                \n");
      out.write("                <div class=\"col-md-2 \">\n");
      out.write("                    <label class=\"form-label\">Gender</label>\n");
      out.write("                    <div class=\"form-check\">\n");
      out.write("                        <input class=\"form-check-input\" type=\"radio\" value=\"male\" name=\"gender\" id=\"flexRadioDefault1\">\n");
      out.write("                        <label class=\"form-check-label\" for=\"flexRadioDefault1\">Male</label>                    \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"col-md-4\">\n");
      out.write("                    <div class=\"form-check mt-4 p-2 \">\n");
      out.write("                        <input class=\"form-check-input \" type=\"radio\" value=\"female\" name=\"gender\" id=\"flexRadioDefault2\" checked>\n");
      out.write("                        <label class=\"form-check-label \" for=\"flexRadioDefault2\"> Female</label>     \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("<!--            </div>-->\n");
      out.write("\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <label>Date of Birth</label>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"dateOfBirth\" name=\"dateOfBirth\" placeholder=\"dd/mm/yyyy\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!----2nd row end-->\n");
      out.write("\n");
      out.write("\n");
      out.write("        <!----3rd row Start-->\n");
      out.write("        <div class=\"row mt-3\">\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div>NID</div>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"nid\" name=\"nid\" placeholder=\"xxxxx\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div>Contact</div>\n");
      out.write("                <input type=\"text\" class=\"form-control\" id=\"contact\" name=\"contact\" placeholder=\"xxxxx\">\n");
      out.write("            </div>\n");
      out.write("        </div>      \n");
      out.write("        <!----3rd row end-->\n");
      out.write("\n");
      out.write("        <!----4th row Start-->\n");
      out.write("        <div class=\"row mt-3\">\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <label class=\"form-label\">Subject</label>\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\">\n");
      out.write("                    <option selected>Select one</option>\n");
      out.write("                    <option value>Honor's</option>\n");
      out.write("                    <option value=\"JEE\">JEE</option>\n");
      out.write("                    <option value=\"DDD\">DDD</option>\n");
      out.write("                    <option value=\"NT\">NT</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-6 mt-2\">\n");
      out.write("                <label>University</label>\n");
      out.write("                <select class=\"form-select\" aria-label=\"Default select example\">\n");
      out.write("                    <option selected>Select one</option>\n");
      out.write("                    <option value=\"Dhaka University\">Dhaka University</option>\n");
      out.write("                    <option value=\"Mokbul Hosen College\">Mokbul Hosen College</option>\n");
      out.write("                    <option value=\"IsDB\">IsDB</option>\n");
      out.write("                    <option value=\"Center College\">Center College</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("        </div>      \n");
      out.write("        <!----4th row end-->      \n");
      out.write("    </form>\n");
      out.write("    <!---- form end---->    \n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<footer class=\"bg-light text-center text-lg-start\">\n");
      out.write("  <!-- Copyright -->\n");
      out.write("  <div class=\"text-center p-3\" style=\"background-color: rgba(0, 0, 0, 0.2);\">\n");
      out.write("    © 2020 Copyright:\n");
      out.write("    <a class=\"text-dark\" href=\"https://mdbootstrap.com/\">MDBootstrap.com</a>\n");
      out.write("  </div>\n");
      out.write("  <!-- Copyright -->\n");
      out.write("</footer>");
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
